Repository pubIO-2020/pubIO, pull requests merged in 2020-06, with the labels that each got.

#24 Update Readme.md
  README.md
Labels: documentation

#34 added onSelect event on markers for iOS to center marker on touch
  pubio/components/screens/Mapview.js
Labels: bug

#65 Sub users on card
  pubio/App.js
  pubio/Firebase
  pubio/assets/profileimages/arial.jpg
  pubio/assets/profileimages/bart.png
  pubio/assets/profileimages/batman.jpg
  pubio/assets/profileimages/beer.png
  pubio/assets/profileimages/darthvader.jpg
  pubio/assets/profileimages/futurama.jpg
  pubio/assets/profileimages/goku.jpg
  pubio/assets/profileimages/greenlantern.jpg
  pubio/assets/profileimages/leela.png
  pubio/assets/profileimages/monk.png
  pubio/assets/profileimages/soldier76.jpg
  pubio/assets/profileimages/wonderwoman.jpg
  pubio/assets/profileimages/yoda.jpg
  pubio/components/Cards.js
  pubio/components/CarouselCards.js
  pubio/components/DrawerContent.js
  pubio/components/Header.js
  pubio/components/screens/Adminview.js
  pubio/components/screens/Cardview.js
  pubio/components/screens/Details.js
  pubio/components/screens/Profileimages.js
  pubio/components/screens/Registerview.js
Labels: MVP, style

#71 Fixed user issues pt.3
  pubio/components/CardScrollView.js
  pubio/components/CarouselCards.js
  pubio/components/Header.js
  pubio/components/Main.js
  pubio/components/screens/Mapview.js
  pubio/components/screens/Userview.js
Labels: MVP, style

#72 69 registration fixes
  pubio/components/CardScrollView.js
  pubio/components/screens/Details.js
  pubio/components/screens/Loginview.js
  pubio/components/screens/Profileimages.js
  pubio/components/screens/Registerview.js
Labels: MVP, bug

#74 Fixed subscribe button issue on press
  pubio/components/screens/Details.js
Labels: MVP, bug

#76 added styling
  pubio/components/DrawerContent.js
  pubio/components/screens/Loginview.js
  pubio/components/screens/Profileimages.js
Labels: style

#79 Update Flowchart
  README.md
Labels: documentation

#80 Update README.md
  README.md
Labels: documentation

#84 Fixed camera permission bug
  pubio/.expo-shared/assets.json
  pubio/.gitignore
  pubio/App.js
  pubio/assets/PubIOSwim.PNG
  pubio/assets/alcohol.png
  pubio/assets/beer.png
  pubio/assets/profileimages/arial.jpg
  pubio/assets/profileimages/darthvader.jpg
  pubio/assets/profileimages/greenlantern.jpg
  pubio/assets/profileimages/wonderwoman.jpg
  pubio/assets/qr-code-black.png
  pubio/components/DrawerContent.js
  pubio/components/Header.js
  pubio/components/screens/Adminview.js
Labels: bug
